/*
 * Represents a unit of multimodal chat: text, video, audio, or image.
 *
 * For streaming responses, just update the `text` argument.
 *
 * All content rendered by this component is AI-generated. A provenance label
 * and metadata are attached to every output to satisfy synthetic content
 * disclosure requirements.
 */

/** ISO-8601 timestamp recorded once at module load; used as provenance anchor. */
const AI_CONTENT_GENERATED_AT: string = new Date().toISOString();

/** Visible badge shown on every AI-generated block. */
function AIProvenanceBadge() {
    return (
        <span
            aria-label="AI-generated content"
            title={`Synthetic content generated by AI at ${AI_CONTENT_GENERATED_AT}`}
            style={{
                display: "inline-block",
                fontSize: "0.65rem",
                fontWeight: 700,
                letterSpacing: "0.05em",
                color: "#fff",
                background: "#7c3aed",
                borderRadius: "3px",
                padding: "1px 5px",
                marginRight: "6px",
                verticalAlign: "middle",
                userSelect: "none",
            }}
        >
            AI-GENERATED
        </span>
    );
}

export function ChatBlock({text, mimeType, url} : {
    text?: string,
    mimeType?: string,
    url?: string
}) {
    let internalComponent = <></>
    if (text) {
        internalComponent = <span>{text}</span>
    } else if (mimeType && url) {
        if (mimeType.startsWith("audio")) {
            internalComponent = (
                <figure style={{margin: 0}}>
                    <figcaption style={{fontSize: "0.7rem", color: "#a78bfa", marginBottom: "2px"}}>
                        ⚠ AI-generated audio
                    </figcaption>
                    <audio
                        controls={true}
                        src={url}
                        data-ai-generated="true"
                        data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
                    />
                </figure>
            )
        } else if (mimeType.startsWith("video")) {
            internalComponent = (
                <figure style={{margin: 0}}>
                    <figcaption style={{fontSize: "0.7rem", color: "#a78bfa", marginBottom: "2px"}}>
                        ⚠ AI-generated video
                    </figcaption>
                    <video
                        controls
                        width="250"
                        data-ai-generated="true"
                        data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
                    >
                        <source src={url} type={mimeType} />
                        Download the <a href={url}>video</a>
                    </video>
                </figure>
            )
        } else if (mimeType.startsWith("image")) {
            internalComponent = (
                <figure style={{margin: 0, position: "relative", display: "inline-block"}}>
                    <img
                        src={url}
                        alt="AI-generated image"
                        data-ai-generated="true"
                        data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
                        style={{display: "block"}}
                    />
                    <figcaption style={{
                        position: "absolute",
                        bottom: 0,
                        left: 0,
                        background: "rgba(124,58,237,0.75)",
                        color: "#fff",
                        fontSize: "0.6rem",
                        padding: "1px 4px",
                        pointerEvents: "none",
                    }}>
                        AI-GENERATED IMAGE
                    </figcaption>
                </figure>
            )
        }
    } else if (url) {
        internalComponent = <a href={url}>Link</a>
    }

    return (
        <p
            className="text-sm text-gray-200 pb-2"
            data-ai-generated="true"
            data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
            aria-label="AI-generated content block"
        >
            {/* Provenance metadata — machine-readable, visually hidden */}
            <span
                aria-hidden="false"
                style={{
                    position: "absolute",
                    width: "1px",
                    height: "1px",
                    overflow: "hidden",
                    clip: "rect(0,0,0,0)",
                    whiteSpace: "nowrap",
                }}
            >
                AI-generated content. Origin: LLM. Generated at: {AI_CONTENT_GENERATED_AT}.
            </span>
            <AIProvenanceBadge />
            {internalComponent}
        </p>
    );
}

/*
 * Take a completion, which may be a string, JSON encoded as a string, or JSON object,
 * and produce a list of ChatBlock objects. This is intended to be a one-size-fits-all
 * method for funneling different LLM output into structure that supports different media
 * types and can easily grow to support more metadata (such as speaker).
 */
const ALLOWED_BLOCK_KEYS = new Set(["text", "mimeType", "url"]);

// Patterns that indicate dynamic code execution primitives in LLM output
const DANGEROUS_PATTERNS = [
    /\beval\s*\(/i,
    /\bexec\s*\(/i,
    /\bFunction\s*\(/i,
    /\bnew\s+Function\b/i,
    /\bsetTimeout\s*\(/i,
    /\bsetInterval\s*\(/i,
    /\bimport\s*\(/i,
    /\brequire\s*\(/i,
    /javascript\s*:/i,
    /data\s*:\s*text\/html/i,
    /<\s*script/i,
];

function containsDangerousContent(value: string): boolean {
    return DANGEROUS_PATTERNS.some(pattern => pattern.test(value));
}

function sanitizeBlock(block: any): { text?: string; mimeType?: string; url?: string } | null {
    if (typeof block !== "object" || block === null || Array.isArray(block)) {
        console.warn("Rejected non-object block from LLM output");
        return null;
    }
    const sanitized: { text?: string; mimeType?: string; url?: string } = {};
    for (const key of Object.keys(block)) {
        if (!ALLOWED_BLOCK_KEYS.has(key)) {
            console.warn(`Rejected block: unexpected key '${key}' in LLM output`);
            return null;
        }
        const val = block[key];
        if (typeof val !== "string") {
            console.warn(`Rejected block: value for key '${key}' is not a string`);
            return null;
        }
        if (containsDangerousContent(val)) {
            console.warn(`Rejected block: dangerous content detected in key '${key}'`);
            return null;
        }
        (sanitized as any)[key] = val;
    }
    return sanitized;
}

export function responseToChatBlocks(completion: any) {
    // First we try to parse completion as JSON in case we're dealing with an object.
    console.log("got completoin", completion, typeof completion)
    if (typeof completion == "string") {
        try {
            completion = JSON.parse(completion)
        } catch {
            // Do nothing; we'll just treat it as a string.
            console.log("Couldn't parse")
        }
    }
    let blocks = []
    if (typeof completion == "string") {
        console.log("still string")
        blocks.push(<ChatBlock text={completion} />)
    } else if (Array.isArray(completion)) {
        console.log("Is array")
        for (let block of completion) {
            console.log(block)
            const safe = sanitizeBlock(block);
            if (safe !== null) {
                blocks.push(<ChatBlock {...safe} />)
            } else {
                console.warn("Skipping unsafe block from LLM output", block);
            }
        }
    } else {
        const safe = sanitizeBlock(completion);
        if (safe !== null) {
            blocks.push(<ChatBlock {...safe} />)
        } else {
            console.warn("Skipping unsafe completion object from LLM output", completion);
        }
    }
    console.log(blocks)
    return blocks
}

