/*
 * Represents a unit of multimodal chat: text, video, audio, or image.
 *
 * For streaming responses, just update the `text` argument.
 *
 * All content rendered by this component is AI-generated. A provenance label
 * and metadata are attached to every output to satisfy synthetic content
 * disclosure requirements.
 */

/** ISO-8601 timestamp recorded once at module load; used as provenance anchor. */
const AI_CONTENT_GENERATED_AT: string = new Date().toISOString();

/**
 * Machine-readable model identifier attached to every provenance record.
 * Update this value whenever the underlying model changes.
 */
const AI_MODEL_ID: string = "ai-model-v1";

/**
 * Computes a cryptographic watermark (HMAC-SHA256) over the model ID and
 * timestamp using the Web Crypto API. The resulting hex digest is embedded
 * as a `data-ai-watermark` attribute on every AI-generated media element,
 * providing a machine-verifiable provenance token beyond visible labels.
 */
async function computeWatermark(modelId: string, timestamp: string): Promise<string> {
    const encoder = new TextEncoder();
    // Use a fixed well-known key material; in production replace with a
    // securely managed secret imported via environment variable / KMS.
    const rawKey = encoder.encode("ai-provenance-watermark-key-v1");
    const cryptoKey = await crypto.subtle.importKey(
        "raw",
        rawKey,
        { name: "HMAC", hash: "SHA-256" },
        false,
        ["sign"]
    );
    const message = encoder.encode(`${modelId}|${timestamp}`);
    const signature = await crypto.subtle.sign("HMAC", cryptoKey, message);
    return Array.from(new Uint8Array(signature))
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");
}

/** React hook that resolves the cryptographic watermark string once on mount. */
function useWatermark(): string {
    const [watermark, setWatermark] = React.useState<string>("");
    React.useEffect(() => {
        computeWatermark(AI_MODEL_ID, AI_CONTENT_GENERATED_AT).then(setWatermark);
    }, []);
    return watermark;
}

/** Visible badge shown on every AI-generated block. */
function AIProvenanceBadge() {
    return (
        <span
            aria-label="AI-generated content"
            title={`Synthetic content generated by AI at ${AI_CONTENT_GENERATED_AT}`}
            style={{
                display: "inline-block",
                fontSize: "0.65rem",
                fontWeight: 700,
                letterSpacing: "0.05em",
                color: "#fff",
                background: "#7c3aed",
                borderRadius: "3px",
                padding: "1px 5px",
                marginRight: "6px",
                verticalAlign: "middle",
                userSelect: "none",
            }}
        >
            AI-GENERATED
        </span>
    );
}

const ALLOWED_URL_HOSTNAMES: ReadonlySet<string> = new Set([
    // Add trusted media-serving hostnames here, e.g.:
    // "cdn.example.com",
    // "media.example.com",
]);

function isSafeUrl(rawUrl: string | undefined): string {
    if (!rawUrl) return "";
    try {
        const parsed = new URL(rawUrl);
        if (parsed.protocol !== "https:") return "";
        if (!ALLOWED_URL_HOSTNAMES.has(parsed.hostname)) return "";
        return rawUrl;
    } catch {
        return "";
    }
}

export function ChatBlock({text, mimeType, url} : {
    text?: string,
    mimeType?: string,
    url?: string
}) {
    const watermark = useWatermark();
    let internalComponent = <></>
    if (text) {
        internalComponent = <span>{text}</span>
    } else if (mimeType && url) {
                const safeUrl = isSafeUrl(url);
        if (mimeType.startsWith("audio")) {
            internalComponent = (
                <figure style={{margin: 0}}>
                    <figcaption style={{fontSize: "0.7rem", color: "#a78bfa", marginBottom: "2px"}}>
                        ⚠ AI-generated audio
                    </figcaption>
                    <audio
                        controls={true}
                        src={safeUrl}
                        data-ai-generated="true"
                        data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
                    />
                </figure>
            )
        } else if (mimeType.startsWith("video")) {
            internalComponent = (
                <figure style={{margin: 0}}>
                    <figcaption style={{fontSize: "0.7rem", color: "#a78bfa", marginBottom: "2px"}}>
                        ⚠ AI-generated video
                    </figcaption>
                    <video
                        controls
                        width="250"
                        data-ai-generated="true"
                        data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
                    >
                        <source src={safeUrl} type={mimeType} />
                        Download the <a href={safeUrl}>video</a>
                    </video>
                </figure>
            )
        } else if (mimeType.startsWith("image")) {
            internalComponent = (
                <figure style={{margin: 0, position: "relative", display: "inline-block"}}>
                    <img
                        src={safeUrl}
                        alt="AI-generated image"
                        data-ai-generated="true"
                        data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
                        style={{display: "block"}}
                    />
                </figure>
            )
        } else if (mimeType.startsWith("video")) {
            internalComponent = (
                <figure style={{margin: 0}}>
                    <figcaption style={{fontSize: "0.7rem", color: "#a78bfa", marginBottom: "2px"}}>
                        ⚠ AI-generated video
                    </figcaption>
                    <video
                        data-ai-model-id={AI_MODEL_ID}
                        data-ai-watermark={watermark}
                        controls
                        width="250"
                        data-ai-generated="true"
                        data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
                    >
                        <source src={sanitizeUrl(url) ?? ""} type={mimeType} />
                        Download the <a href={sanitizeUrl(url) ?? "#"}>video</a>
                    </video>
                </figure>
            )
        } else if (mimeType.startsWith("image")) {
            internalComponent = (
                <figure style={{margin: 0, position: "relative", display: "inline-block"}}>
                    <img
                        src={sanitizeUrl(url) ?? ""}
                        alt="AI-generated image"
                        data-ai-generated="true"
                        data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
                        style={{display: "block"}}
                    />
                    <figcaption style={{
                        position: "absolute",
                        bottom: 0,
                        left: 0,
                        background: "rgba(124,58,237,0.75)",
                        color: "#fff",
                        fontSize: "0.6rem",
                        padding: "1px 4px",
                        pointerEvents: "none",
                    }}>
                        AI-GENERATED IMAGE
                    </figcaption>
                </figure>
            )
        }
    } else if (url) {
        const safeUrl = isSafeUrl(url);
        internalComponent = safeUrl ? <a href={safeUrl}>Link</a> : <span>[blocked URL]</span>
    }

    return (
        <p
            className="text-sm text-gray-200 pb-2"
            data-ai-generated="true"
            data-ai-provenance-timestamp={AI_CONTENT_GENERATED_AT}
            aria-label="AI-generated content block"
        >
            {/* Provenance metadata — machine-readable, visually hidden */}
            <span
                aria-hidden="false"
                style={{
                    position: "absolute",
                    width: "1px",
                    height: "1px",
                    overflow: "hidden",
                    clip: "rect(0,0,0,0)",
                    whiteSpace: "nowrap",
                }}
            >
                AI-generated content. Origin: LLM. Generated at: {AI_CONTENT_GENERATED_AT}.
            </span>
            <AIProvenanceBadge />
            {internalComponent}
        </p>
    );
}

/*
 * Take a completion, which may be a string, JSON encoded as a string, or JSON object,
 * and produce a list of ChatBlock objects. This is intended to be a one-size-fits-all
 * method for funneling different LLM output into structure that supports different media
 * types and can easily grow to support more metadata (such as speaker).
 */
const ALLOWED_BLOCK_KEYS = new Set(["text", "mimeType", "url"]);

/**
 * Strictly validate a URL to only allow safe, absolute http/https URLs.
 * Returns the original url string if safe, or null if the URL is unsafe or unparseable.
 * This prevents XSS via javascript:, data:, vbscript:, and other dangerous schemes.
 */
function sanitizeUrl(url: string): string | null {
    try {
        const parsed = new URL(url);
        if (parsed.protocol === "https:" || parsed.protocol === "http:") {
            return url;
        }
        return null;
    } catch {
        return null;
    }
}

/**
 * Validate that a field value is safe for use.
 * For URL fields, only allow http/https via sanitizeUrl.
 * For text fields, we rely on React's built-in JSX escaping (no innerHTML);
 * no regex blocklist is used because blocklists are bypassable.
 */
function containsDangerousContent(value: string, fieldName?: string): boolean {
    if (fieldName === "url") {
        // For URL fields, reject anything that is not a safe http/https URL
        return sanitizeUrl(value) === null;
    }
    // For non-URL text fields rendered via React JSX (not dangerouslySetInnerHTML),
    // React escapes the content automatically — no additional regex check needed.
    return false;
}

function sanitizeBlock(block: any): { text?: string; mimeType?: string; url?: string } | null {
    if (typeof block !== "object" || block === null || Array.isArray(block)) {
        console.warn("Rejected non-object block from LLM output");
        return null;
    }
    const sanitized: { text?: string; mimeType?: string; url?: string } = {};
    for (const key of Object.keys(block)) {
        if (!ALLOWED_BLOCK_KEYS.has(key)) {
            console.warn(`Rejected block: unexpected key '${key}' in LLM output`);
            return null;
        }
        const val = block[key];
        if (typeof val !== "string") {
            console.warn(`Rejected block: value for key '${key}' is not a string`);
            return null;
        }
        if (containsDangerousContent(val)) {
            console.warn(`Rejected block: dangerous content detected in key '${key}'`);
            return null;
        }
        (sanitized as any)[key] = val;
    }
    return sanitized;
}

export function responseToChatBlocks(completion: any) {
    // First we try to parse completion as JSON in case we're dealing with an object.
    console.log("got completoin", completion, typeof completion)
    if (typeof completion == "string") {
        try {
            completion = JSON.parse(completion)
        } catch {
            // Do nothing; we'll just treat it as a string.
            console.log("Couldn't parse")
        }
    }
    let blocks = []
    if (typeof completion == "string") {
        console.log("still string")
        if (containsDangerousContent(completion)) {
            console.warn("Rejected plain-string completion: dangerous content detected in LLM output");
        } else {
            blocks.push(<ChatBlock text={completion} />)
        }
    } else if (Array.isArray(completion)) {
        console.log("Is array")
        for (let block of completion) {
            console.log(block)
            const safe = sanitizeBlock(block);
            if (safe !== null) {
                blocks.push(<ChatBlock {...safe} />)
            } else {
                console.warn("Skipping unsafe block from LLM output", block);
            }
        }
    } else {
        const safe = sanitizeBlock(completion);
        if (safe !== null) {
            blocks.push(<ChatBlock {...safe} />)
        } else {
            console.warn("Skipping unsafe completion object from LLM output", completion);
        }
    }
    console.log(blocks)
    return blocks
}

